### PR TITLE
feat(attachment-canvas): render spreadsheet formulas and CSV

### PR DESCRIPTION
**Pull request by valerydluski**
**Description:**

Render CSV attachments with the same `@silurus/ooxml` spreadsheet engine used for XLSX. XLSX previews now keep a stable Excel-style `fx` bar visible above the sheet: it shows the selected cell's formula when present, otherwise its formatted display value, and reserves the same height for empty or unselected cells. Upgrade `@silurus/ooxml` from 0.80.2 to 0.86.1 and wire its optional ChartEx module into Office viewers to preserve chart rendering after the upgrade. CSV fields remain text, including leading zeroes and values beginning with `=`.

Verified with attachment-canvas tests (224/224), targeted chat-hooks tests (73/73), typechecks, lint, formatting, and documentation validation. The complete chat-hooks suite still has two pre-existing environment-specific failures in `create-files-api.spec.ts` (`Response(new Blob(...)).stream is not a function`); the changed chat-hooks test file passes independently.

**UI changes**

XLSX preview with formula bar

Spreadsheet preview

**Checklist:**

- [x] the pull request name complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] the pull request name starts with `feat(attachment-canvas):`
- [ ] the pull request name ends with an issue reference (not applicable: no ticket for this change)
- [x] I confirm that do not share any confidential information like API keys or any other secrets and private URLs

### CODE REVIEW

**Review by Alexander-Kezik — DISMISSED** [review]

File: libs/attachment-canvas/src/components/OoxmlContent/OoxmlContent.module.scss [hunk 1]
```diff
@@ -2,6 +2,30 @@
   background: var(--ac-ooxml-bg, var(--bg-layer-raised, #fcfcfc));
 }
 
+.spreadsheetCanvas {
```
Comment (PolinaGurinovich97) [inline libs/attachment-canvas/src/components/OoxmlContent/OoxmlContent.module.scss:5]: use tailwind

**Review by PolinaGurinovich97 — APPROVED** [review]
